# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 9000, host: 9000 # play

  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
  end

  config.vm.provision :puppet do |puppet| 
     puppet.module_path = "dev_env/puppet_modules" 
     puppet.manifests_path = "dev_env/manifests"
  end
end
